coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  unit:
    carryforward: true
  integration:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
