FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/juno-lan-agent ./cmd/juno-lan-agent

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/bin/juno-lan-agent .

CMD ["./juno-lan-agent"]
