FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/juno-web ./cmd/juno-web

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/bin/juno-web .

CMD ["./juno-web"]
