global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: juno-server
    static_configs:
      - targets: ['conductor:6004']
        labels:
          service: juno-server
