// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: juno.proto

#include "juno.pb.h"
#include "juno.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace juno {
namespace api {

static const char* JunoService_method_names[] = {
  "/juno.api.JunoService/Ping",
};

std::unique_ptr< JunoService::Stub> JunoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< JunoService::Stub> stub(new JunoService::Stub(channel, options));
  return stub;
}

JunoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(JunoService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status JunoService::Stub::Ping(::grpc::ClientContext* context, const ::juno::api::PingRequest& request, ::juno::api::PongResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::juno::api::PingRequest, ::juno::api::PongResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void JunoService::Stub::async::Ping(::grpc::ClientContext* context, const ::juno::api::PingRequest* request, ::juno::api::PongResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::juno::api::PingRequest, ::juno::api::PongResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void JunoService::Stub::async::Ping(::grpc::ClientContext* context, const ::juno::api::PingRequest* request, ::juno::api::PongResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::juno::api::PongResponse>* JunoService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::juno::api::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::juno::api::PongResponse, ::juno::api::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::juno::api::PongResponse>* JunoService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::juno::api::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

JunoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      JunoService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< JunoService::Service, ::juno::api::PingRequest, ::juno::api::PongResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](JunoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::juno::api::PingRequest* req,
             ::juno::api::PongResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

JunoService::Service::~Service() {
}

::grpc::Status JunoService::Service::Ping(::grpc::ServerContext* context, const ::juno::api::PingRequest* request, ::juno::api::PongResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace juno
}  // namespace api

