name: Juno Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Install tools
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.16.3

      - name: Generate code
        run: make generate

      - name: Run unit tests
        run: make unit-test

      - name: Build container image
        run: make docker-build

      - name: Start container
        run: make docker-up

      - name: Run integration tests
        run: make integration-test

      - name: Stop container
        run: make docker-down