name: Juno Test Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Install deps
        run: |
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.16.3
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
      - name: Generate code
        run: make generate
      - name: Run formatter
        run: make test-fmt
      - name: Run linter
        run: make lint
      - name: Run vet
        run: make vet

  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Install tools
        run: |
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.16.3
          go install github.com/boumenot/gocover-cobertura@latest
      - name: Generate code
        run: make generate
      - name: Build binaries
        run: make build
      - name: Run unit tests with coverage
        run: make unit-test-cover
      - name: Upload unit coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ut-coverage.txt
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}

  functional-tests:
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Download dependencies
        run: go mod download
      - name: Install tools
        run: |
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.16.3
          go install github.com/boumenot/gocover-cobertura@latest
      - name: Generate code
        run: make generate
      - name: Build binaries with coverage
        run: make coverage-build
      - name: Generate test venv
        run: make test-venv
      - name: Run functional tests
        run: make functional-tests
      - uses: actions/upload-artifact@v7
        with:
          name: logs
          path: ./logs
      - name: Merge coverage profiles
        run: make generate-coverage
      - name: Upload functional coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/functional-coverage.txt

  docker-build:
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build lan agent container
        run: |
          docker build -f Dockerfile.lanagent . -t juno-lan-agent:latest
      - name: Build conductor container
        run: |
          docker build -f Dockerfile.conductor . -t juno-conductor:latest
      - name: Make test venv
        run: make test-venv
      - name: Generate deployments
        run: |
          ./cicd/generate-deployment.sh test ./conf/.env.example core
          ./cicd/generate-deployment.sh test ./conf/.env.example edge
      - name: Run containers
        run: |
          docker compose --project-name juno --file ./deployments/core/test/docker-compose.core.yaml up -d postgres
          docker compose --project-name juno --file ./deployments/core/test/docker-compose.core.yaml up -d conductor
          docker compose --project-name juno --file ./deployments/core/test/docker-compose.core.yaml up -d nginx
          docker compose --project-name juno --file ./deployments/edge/test/docker-compose.edge.yaml up -d lan-agent
      - name: Run smoke tests
        run: make docker-smoke-tests
          
